### ISSUE TITLE
[Feature Request] Don't update pinned dependencies

### ISSUE THREAD

**Issue by JimiC** [leftstick/vscode-npm-dependency#2]
I'd like to request the ability for the extension to not update pinned dependencies. The whole point of pinned dependencies is to remain at that version no matter what.

**Comment by JimiC** [comment]
Consider using [semver](https://www.npmjs.com/package/semver) to help you determine whether a dependency should be updated and to what version.
Info: https://docs.npmjs.com/misc/semver

**Comment by leftstick** [comment]
@JimiC  you can now by change `npm. updateStrategy` to `SEMVER` for your purpose
