### ISSUE TITLE
Which font and color scheme are used in example gif?

### ISSUE THREAD

**Issue by menzow** [leftstick/vscode-npm-dependency#3]
Sorry for opening an issue for this but I'm really liking the color scheme and font used in the example gif. Mind sharing the configuration?

**Comment by leftstick** [comment]
For font-icon, i am using [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)

For color theme, i am using [Dracula Soft](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)

Hope you enjoy ^^
