### ISSUE TITLE
Doesn't work behind corporate proxy

### ISSUE THREAD

**Issue by ThePlenkov** [leftstick/vscode-npm-dependency#4]
Hi!

Cool idea - it really beats now yarn and npm )) however doesn't work now with a proxy server. 

Do you use any agent to when sending requests to npm? Thanks!

**Comment by leftstick** [comment]
You mean you have `http.proxy` in your `settings.json`? And you want it to be used in this extension, right?

**Comment by ThePlenkov** [comment]
>You mean you have `http.proxy` in your `settings.json`? And you want it to be used in this extension, right?

@leftstick actually i have iT everywhere)) os settings, va code settings, npm config, even http_proxy environment variable.

Once you have it - you have to declare it everywhere))

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ThePlenkov** [comment]
It could be great if you manage to reuse vs code settings to make it consistent 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leftstick** [comment]
try `1.2.1`, now `http.proxy` is supported, you can try it with your env

**Comment by ThePlenkov** [comment]
Hi! I tried. It is still failing with the following popup:

write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:827:
. Please check if your registry is accessible

**Comment by ThePlenkov** [comment]
http.proxy is set like http://webproxy.corp.com:1234

**Comment by leftstick** [comment]
@ThePlenkov try `1.2.2`, i use `axios` internally for making all requests, but there is a bug with it.

**Comment by ThePlenkov** [comment]
> @ThePlenkov try `1.2.2`, i use `axios` internally for making all requests, but there is a bug with it.

Hi, the problem hasn't gone but the message is different now:

![image](https://user-images.githubusercontent.com/6381507/49868467-d4061b00-fe0d-11e8-84bc-3f8bb244a940.png)

**Comment by leftstick** [comment]
this is weird, i tried with my proxy setup, `"http.proxy": "http://127.0.0.1:1087"`, it's working, are you sure your proxy is valid?

**Comment by ThePlenkov** [comment]
>this is weird, i tried with my proxy setup, `"http.proxy": "http://127.0.0.1:1087"`, it's working, are you sure your proxy is valid?

@leftstick sure, pretty much. I have all the services working with proxy. Even my own node js code - without proxy agent it returns same error.

Might it be something related to strict ssl?

Sometimes I have to set it as false.

Meanwhile I will try also a corporate npm artifactory registry. May be then it will work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
