### ISSUE TITLE
ERROR - write EPROTO 2810572872:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Steve-Mcl** [leftstick/vscode-npm-dependency#7]
![image](https://user-images.githubusercontent.com/44235289/90604344-9bc6fa80-e1f4-11ea-90e4-e5e18772c61d.png)

This may be related to being behind a corporate proxy.

NOTE: my Browser, NPM, Git etc all connect to internet, this extension does not. I suspect the extension may not be using settings from NPM config.  In particular, `registry = "http://registry.npmjs.org/"` and `strict-ssl = false`  AND/OR reading env vars for HTTP_PROXY, HTTPS_PROXY and NO_PROXY?

**Comment by Steve-Mcl** [comment]
UPDATE: 
I edited the setting **NPM: Registry** and removed the s from `https` and now it works.

**Comment by leftstick** [comment]
@Steve-Mcl nice job. Thanks for you sharing
